POST http://localhost:3000/homework
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRsdXJhayIsImlhdCI6MTY5MDI4MTU3MiwiZXhwIjoxNjkwMjg1MTcyfQ.OZkeojnyL7EFu6AaWKqBqNdWyf2fyJNwkygkHwcBvbM

{
    "className": "class",
    "from": {
        "year": 2019,
        "month": 1,
        "day": 1
    },
    "assignments": [
        {
            "subject": "Mathe",
            "description": "Aufgabe 1",
            "due": {
                "month": 1,
                "year": 2019,
                "day": 2
            }
        }
    ]
}