PATCH localhost:3000/auth/request/64e61ed936475a58be01f54b/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRsdXJhayIsImlhdCI6MTY5MjgxMjQ4NywiZXhwIjoxNjkyODE2MDg3fQ.E4MQH9c3PaG4t_WBW8N_nmN_hcyaZA5qkDl9QQ_csMA
